import './js/agreement';
import './js/animation';
import './js/flip-card';
import './js/menu';
import './js/modal';
import './js/to-top';
import './js/about-btn';
import './js/smooth-scroll';
import './js/slider';
