import './js/agreement';
import './js/animation';
import './js/flip-card';
import './js/menu';
import './js/modal';
import './js/to-top';
import './js/readmore-prod';
import './js/readmore-about';
import './js/smooth-scroll';
